sudo: false

language: android

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository

before_install:
  - git clone --depth 1 https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle

script:
  - ./gradlew build